name: 'custom example action'
description: 'An example action that prints a message'

inputs:
  github-token:
    description: 'The GitHub token for authentication'
    required: true
  label:
    description: 'The label to be applied to the pull request'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
