name: 'Hello World'

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        with:
          name: 'GitHub'
