name: 'Hello World'

on:
  pull_request:
    types: [opened, reopened]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          label: 'needs-review'
